dataset:
  preference_dataset: "gs://vertex-ai/generative-ai/rlhf/text_small/summarize_from_feedback_tfds/comparisons/train/*.jsonl"
  prompt_dataset: "gs://vertex-ai/generative-ai/rlhf/text_small/reddit_tfds/train/*.jsonl"
  eval_dataset: "gs://vertex-ai/generative-ai/rlhf/text_small/reddit_tfds/val/*.jsonl"
  preference_size: 3000
  prompt_size: 2000

training:
  large_model_reference: "llama-2-7b"
  reward_model_train_steps: 1410
  reinforcement_learning_train_steps: 320
  reward_model_learning_rate_multiplier: 1.0
  reinforcement_learning_rate_multiplier: 1.0
  kl_coeff: 0.1
  instruction: "Summarize in less than 50 words"
  batch_size: 64